package aplikasi.model;
// Generated Jan 6, 2017 1:53:27 AM by Hibernate Tools 5.2.0.CR1

/**
 * Sparepart generated by hbm2java
 */
public class Sparepart implements java.io.Serializable {

	private Integer id;
	private int idSpareparts;
	private String nama;
	private String merk;
	private int harga;

	public Sparepart() {
	}

	public Sparepart(int idSpareparts, String nama, String merk, int harga) {
		this.idSpareparts = idSpareparts;
		this.nama = nama;
		this.merk = merk;
		this.harga = harga;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdSpareparts() {
		return this.idSpareparts;
	}

	public void setIdSpareparts(int idSpareparts) {
		this.idSpareparts = idSpareparts;
	}

	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	public String getMerk() {
		return this.merk;
	}

	public void setMerk(String merk) {
		this.merk = merk;
	}

	public int getHarga() {
		return this.harga;
	}

	public void setHarga(int harga) {
		this.harga = harga;
	}

}
