package aplikasi.model;
// Generated Jan 7, 2017 1:48:23 AM by Hibernate Tools 5.2.0.CR1

/**
 * Sparepart generated by hbm2java
 */
public class Sparepart implements java.io.Serializable {

	private Integer id;
	private Integer idSpareparts;
	private String nama;
	private String merk;
	private Integer harga;

	public Sparepart() {
	}

	public Sparepart(Integer idSpareparts, String nama, String merk, Integer harga) {
		this.idSpareparts = idSpareparts;
		this.nama = nama;
		this.merk = merk;
		this.harga = harga;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getIdSpareparts() {
		return this.idSpareparts;
	}

	public void setIdSpareparts(Integer idSpareparts) {
		this.idSpareparts = idSpareparts;
	}

	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	public String getMerk() {
		return this.merk;
	}

	public void setMerk(String merk) {
		this.merk = merk;
	}

	public Integer getHarga() {
		return this.harga;
	}

	public void setHarga(Integer harga) {
		this.harga = harga;
	}

}
